nginx:
  image: sin30/nginx
  env_file: .env
  ports:
   - 80:80
   - 443:443
  links:
   - php-fpm

php-fpm:
  image: sin30/php-fpm
  env_file: .env
  links:
   - mysql
   - redis
  volumes:
   - ~/Code/Dockerfiles/html:/data/scripts

mysql:
  image: sin30/mysql
  env_file: .env
  ports:
   - 3306:3306
  volumes:
   - /data/mysql:/var/lib/mysql

redis:
  image: sin30/redis
  env_file: .env
  ports:
   - 6379:6379
  volumes:
   - /data/redis:/data
