nginx:
  image: sin30/nginx
  env_file: .env
  ports:
   - 80:80
   - 443:443
  links:
   - php-fpm

php-fpm:
  image: sin30/php-fpm
  env_file: .env
  links:
   - mysql
   - redis

mysql:
  image: sin30/mysql
  env_file: .env

redis:
  image: sin30/redis
  env_file: .env
